### ISSUE TITLE
Ref_label and expr_label in notebook tutorial switched

### ISSUE THREAD

**Issue by ArturDev42** [vandijklab/CINEMA-OT#11] opened 2024-05-27 16:44 UTC
Thanks for this interesting method! In`cinemaot_tutorial.ipynb` I noticed that the `ref_label` is set to the treatment **IFNb**. 

```
cf, ot, de = co.cinemaot.cinemaot_unweighted(
    adata_,
    obs_label="perturbation",
    ref_label="IFNb",
    expr_label="No stimulation",
    mode="parametric",
    thres=0.5,
    smoothness=1e-5,
    eps=1e-3,
    preweight_label="cell_type0528",
)
```

From the source code `cinemaot.py` I understand that the `ref_label` indicates the control group.
```
ref_label: 'str'
        A string for indicating the control group in adata.obs.values.
```
I assume that in the example above it should be `ref_label="No stimulation"` and `expr_label="IFNb"`, correct? Thanks!

**Comment by MingzeDong** [comment] 2024-10-28 20:09
Thanks for bringing this up! This problem arises from our early experiments when we switched "treatment effect on control cells" to "treatment effect on perturbed cells". This is fixed in the newer Pertpy implementation: https://github.com/scverse/pertpy .

**Comment by Joeyars** [comment] 2024-11-05 21:10
Hi Mingze, 

Thanks for developing CINEMA-OT! Awesome strategy to identify perturbation. 
I have a question regarding ref and expr. If I understand right,  (Treatment - Control) should generate similar response matrix with (Control - Treatment) as the only difference between them is the treatment.  I find that in some of my analysis, the response matrix are quite different when switching ref and expr. In one way, I get a group of cells show different response with others which is very interesting to me, but this group of cells are not observable if I switch ref and expr. Two samples have similar cell numbers. My samples are more heterozygous than the data used in the paper with many more cell types. I was thinking that the cell type abundance difference may affect the result, but technically they should be same. Do you have any suggestion or comment on that? 

Thank you!  
Joey

**Comment by MingzeDong** [comment] 2024-11-14 08:57
Hi Joey, Thanks for the question. Actually, Treatment - Control and Control - Treatment can be different, for example, in an experiment where a perturbation randomly affects 50% cell of the same type. Then the ground truth treatment effect on treated cells should show two distinct clusters (perturbed versus non-perturbed). On the other hand, the ground truth treatment on control cells has only one value (corresponding to the average status). This actually constitutes a case (more or less) uniquely addressed by CINEMA-OT.

Nevertheless, an evaluation of these cell populations is necessary. One sanity check is whether the cell types are correctly aligned on the corrected confounder space (details can be seen in the tutorial). If there is a problem, one approach to fix the issue is to provide the annotation labels to the cinemaot function (also mentioned in the tutorial, not sure if you tried it). Finally, although this issue is unlikely due to the inconsistency of the OT map, the pertpy version of CINEMA-OT is more polished and uses a better OT solver. 

Best,
Mingze

**Comment by Joeyars** [comment] 2024-11-15 20:54
> Hi Joey, Thanks for the question. Actually, Treatment - Control and Control - Treatment can be different, for example, in an experiment where a perturbation randomly affects 50% cell of the same type. Then the ground truth treatment effect on treated cells should show two distinct clusters (perturbed versus non-perturbed). On the other hand, the ground truth treatment on control cells has only one value (corresponding to the average status). This actually constitutes a case (more or less) uniquely addressed by CINEMA-OT.
> 
> Nevertheless, an evaluation of these cell populations is necessary. One sanity check is whether the cell types are correctly aligned on the corrected confounder space (details can be seen in the tutorial). If there is a problem, one approach to fix the issue is to provide the annotation labels to the cinemaot function (also mentioned in the tutorial, not sure if you tried it). Finally, although this issue is unlikely due to the inconsistency of the OT map, the pertpy version of CINEMA-OT is more polished and uses a better OT solver.
> 
> Best, Mingze

Thanks! This helps a lot!

**Closed as completed** 2024-12-12 00:37 UTC
